---
- name: Converge
  hosts: all
  become: true

  vars:
    prometheus_node_exporter_enabled_collectors:
      - logind
    prometheus_node_exporter_disabled_collectors:
      - netstat

  roles:
    - role: ansible-role-prometheus-node-exporter

  post_tasks:
    - name: Restart any services before running the tests
      meta: flush_handlers

    - name: Give the Node Exporter time to start
      pause:
        seconds: 30

    - name: Verify that the Node Exporter is running on port 9100
      uri:
        url: http://127.0.0.1:9100
        status_code: 200
